# from https://github.com/aseem-hegshetye/gha-files-changed/blob/main/.github/workflows/files_changed.yaml
#
# If any file in input folder_path was changed then return true else return false
# echo all changed files
# for PUSH event - compare current commit with previous commit
# for PULL_REQUEST event - compare source branch with target branch
name: If files in folder_path were changed

on:
  workflow_call:
    outputs:
      all_changed_files:
        description: List of all changed files in folder_path input
        value: ${{ jobs.if-file-changed.outputs.all_changed_files }}
      boolean_output:
        description: true - if files in folder_path were changed. else false.
        value: ${{ jobs.if-file-changed.outputs.boolean_output }}
    inputs:
      # To find files with extensions .yml and .yaml, you can set the folder_path variable to the directory you want to search in.
      # For example, to search in the current directory and its subdirectories, you can set folder_path to "./**/*.yml ./**/*.yaml".
      folder_path:
        required: true
        type: string

jobs:
  if-file-changed:
    name: Check if files changed
    runs-on: ubuntu-latest
    outputs:
      boolean_output: ${{ steps.get_output.outputs.boolean_output }}
      all_changed_files: ${{ steps.get_output.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history of all branches

      - name: Get files changed on push
        if: github.event_name=='push' && contains(fromJson('["dev", "master","main"]'), github.ref_name)
        id: files_changed_on_push
        run: |
          all_changed_files=$(git --no-pager diff --name-only HEAD^ HEAD)
          echo "all_changed_files=$all_changed_files" >> $GITHUB_OUTPUT

      - name: Get files changed when pr is created/updated
        if: github.event_name=='pull_request'
        id: files_changed_on_pr
        run: |
          git symbolic-ref refs/remotes/origin/HEAD origin/${{github.base_ref}}
          all_changed_files=$(git --no-pager diff --name-only origin/${{github.head_ref}} origin/${{github.base_ref}})
          echo "all_changed_files='$all_changed_files'" >> $GITHUB_OUTPUT

      - name: Get combined boolean output
        id: get_output
        run: |
          if [[ ${{ steps.files_changed_on_push.outcome }} == "success" ]]; then
            all_changed_files=${{ steps.files_changed_on_push.outputs.all_changed_files }}
          elif [[ ${{ steps.files_changed_on_pr.outcome }} == "success" ]]; then
            all_changed_files=${{ steps.files_changed_on_pr.outputs.all_changed_files }}
          fi
          
          echo "all files changed are -"
          echo $all_changed_files
          
          echo "all_changed_files=$all_changed_files" >> $GITHUB_OUTPUT
          echo "boolean_output=false" >> $GITHUB_OUTPUT
          for file in $all_changed_files; do
            echo "file = $file"
            if [[ $file == ${{inputs.folder_path}} ]]; then
              echo "file matches folder_path pattern"
              echo "boolean_output=true" >> $GITHUB_OUTPUT
              break
            fi
          done
