name: Validate App Specs

on:
  pull_request:
    paths:
      - '.do/*.yaml'
      - '.do/*.yml'
  workflow_dispatch:

jobs:
  find-changes:
    name: Identify Changed App Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history of all branches
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

  propose-app-spec:
    needs: find-changes
    name: Validate App Spec -  ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.find-changes.outputs.files.outputs.added_modified) }}
    environment: propose-app-spec
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Propose App Spec
        run: doctl apps propose --spec "${{ matrix.file }}"
      - name: Another Command
        run: echo "Running another command for ${{ matrix.file }}"
