name: Validate App Specs

on:
  pull_request:
    paths:
      - '.do/*.yaml'
      - '.do/*.yml'
  workflow_dispatch:

jobs:
  find-changes:
    name: Identify Changed App Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history of all branches
      - name: "Get Changed Files: do/*.y?ml"
        uses: ./.github/workflows/get-changed-files.yaml
        with:
          folder_path: .do/**/*.yml .do/**/*.yaml

  propose-app-spec:
    needs: find-changes
    name: Validate App Spec -  ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ needs.find-changes.outputs.all_changed_files }}
    environment: propose-app-spec
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Propose App Spec
        run: doctl apps propose --spec "${{ matrix.file }}"
      - name: Another Command
        run: echo "Running another command for ${{ matrix.file }}"
