name: Validate App Specs

on:
  pull_request:
    paths:
      - '.do/*.yaml'
      - '.do/*.yml'
  workflow_dispatch:

jobs:
  find-changes:
    name: Identify Changed App Specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history of all branches
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Filter Changed Files
        id: filtered_files
        run: |
          files_array=()
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            if [[ "$changed_file" == .do/*.yaml || "$changed_file" == .do/*.yml ]] && [[ "$changed_file" != .do/*.template.yaml ]]; then
              files_array+=("$changed_file")
            fi
          done
          files_json=$(printf '%s\n' "${files_array[@]}" | jq -R . | jq -s .)
          echo "Collected files: $files_json"
          echo "added_modified=$files_json" >> $GITHUB_OUTPUT
    outputs:
      added_modified: ${{ steps.filtered_files.outputs.added_modified }}

  propose-app-spec:
    needs: find-changes
    name: Validate App Spec -  ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJSON(needs.find-changes.outputs.added_modified) }}
    environment: propose-app-spec
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Propose App Spec
        run: doctl apps propose --spec "${{ matrix.file }}"
      - name: Another Command
        run: echo "Running another command for ${{ matrix.file }}"
